apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test-pod
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - name: test-pod
    image: zalerix/rest-test
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
    ports:
      - containerPort: 4567
    env:
      - name: COLOR
        value: blue
    envFrom:
      - configMapRef:
          name: app-config
      - secretRef:
          name: app-secret
    securityContext:
      runAsUser: 1000
      capabilities:
        add: ['MAC_ADMIN']
  tolerations:
    - key: app
      operator: "Equal"
      value: blue
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: size
              operator: In
              values:
                - "Large" 
#  nodeSelector:
#    size: Large
  
      
