apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-persistent-volume-claim
spec:
  resources:
    requests:
      storage: 50Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
