apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test-pod
    function: rest
  annotations:
    version: 1.0.0
spec:
  restartPolicy: Never
  containers:
    - name: test-pod
      image: zalerix/rest-test
      resources:
        limits:
          memory: "64Mi"
          cpu: "100m"
      ports:
        - containerPort: 4567
