apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test-pod
spec:
  containers:
    - name: test-pod
      image: zalerix/rest-test
      resources:
        limits:
          memory: "64Mi"
          cpu: "100m"
      ports:
        - containerPort: 4567
      readinessProbe:
        httpGet:
          path: "/"
          port: 4567
        initialDelaySeconds: 5
        periodSeconds: 3
        failureThreshold: 5
      livenessProbe:
        httpGet:
          path: "/"
          port: 4567
        periodSeconds: 5
        failureThreshold: 1
